# HTML/CSS/JS static files run කරන්න Nginx base image එකක් භාවිතය
FROM nginx:alpine

# ඔයාගේ Frontend files ටික Nginx web server එකට copy කිරීම
COPY . /usr/share/nginx/html

# Web Server port එක Expose කිරීම
EXPOSE 80