server:
  port: 8083

spring:
  application:
    name: order-service
  data:
    mongodb:
      # Local run කරද්දී localhost ලෙසත්, env variable එකක් දුන්නොත් එකෙනුත් ගන්න විදිහට:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://order-mongodb-container:27017/bookstore_db}

app:
  api:
    key: YOUR_SECRET_API_KEY_HERE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs